sudo: required

dist: xenial

services:
  - docker

language: go

go:
  - "1.12"

# Sets ${VER} to be MAJOR.MINOR from git tag, IF available,
#
# ${SLUG} removes "docker-" prefix, which while useful on GH, is useless on Docker Hub
env:
  global:
    - VER=$(echo ${TRAVIS_TAG} | cut -d. -f1,2)

stages:
  - build
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: build
      name: "Build Docker image for amd64"
      env: ARCH=linux-amd64

    - name: "Build Docker image for arm32v6"
      env: ARCH=linux-armv6

    - name: "Build Docker image for arm32v7"
      env: ARCH=linux-armv7

    - stage: deploy
      name: "Aggregate Docker images under one manifest"
      script: ./travis/docker-manifest.sh

    - name: "Upload Go binaries to Github Releases"
      deploy:
        skip_cleanup: true
        provider: releases
        api_key:
          secure: gTnlDmpy3QA5rMBzsiRqjzbYFryruy8bgUznT3a/Ay6YE9dMSULpAf17bd/O05NTgT2iadjMnSTbCpGKmeDnAdVOk42ZTx9Gxtr983wsMcfzKbVd04BTtsPISB7DGH3Gc9ZyLRJCXadR9zHsWC9DsxVU8MMIom+DBPs2Xw6lByl7NH/tjcnzw0YBAxbKQW0jiX0OUW6cTwsfGtB2HE+JYJOshHaw3Am40TJl3ZHaTtVfpBTVWoQbIqgh7wZTpSHdcHQA3NZS35Qp/tRI8gZq37FbAUMqw8AYR4vveqT/6xVVElp/SQN2Qb4mvu/CAfGcAT7SiNjjwin67/whhBq9GG2smA+E0h5Fa9oODbNH5m39x0b5yuO/qHjzW1tdFCh3lfttlruYbqjogDdJDVjj3HSyjYYslhfc/l7JLM7MIXTKZes9s4jtTXQQ41njum0+pUCn+h1fJtb2wRVF45HgejPn+EUxUch9pkaNJXp+yR4HjY5e/NCH2NDoz3hmoysjO5xotr2YVVOiYbfMkQqIZ1hsE971Q5tbfVE1+1HKYl+FESvbFyJLNNCCyyx6Iqc6sHVyomsSj/4E+MujQX2GPeSSZMep2MqJS+GDYidSgyWyIera+rgxds2TgazBl8xi94Oeln+BZUbLhRqyZ8vTiTndUuWV1h8gGaFeXrMvNeY=
        file_glob: true
        file: bin/*.tgz
        on:
          repo: lncm/invoicer
          tags: true


before_script: ./travis/before-script.sh
script: ./travis/script.sh
