name: Update Docker Hub README everytime it changes on master

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - '.github/workflows/update-readme.yml'

jobs:
  sync:
    name: Update README to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.0.0

      # Disabled because:
      # 1.  When DOCKER_TOKEN is used the returned login token doesn't have the perm to sync README any more
      # 2. Impossible to use DOCKER_PASS when 2FA is enabled :/
      - name: Sync README.md and Description to Docker Hub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USER }}
          pass: ${{ secrets.DOCKER_PASS }}
          description: true
