name: Update Docker Hub README everytime it changes on master

on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  sync:
    name: Update README to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Sync README.md and Description to Docker Hub
        uses: meeDamian/sync-readme@v1.0.5
        with:
          user: meedamian
          pass: ${{secrets.DOCKER_TOKEN}}
          description: true
